.PHONY: start start-prod stop logs clean build dev-backend dev-frontend setup check test-shell lint-backend .env kiro-login

# ─── Configuration ───────────────────────────────────────────────────────────
APP_NAME    := kronn
PORT        := 3140
DOCKER_COMP := docker compose

# ─── Colors ──────────────────────────────────────────────────────────────────
RED    := \033[0;31m
GREEN  := \033[0;32m
YELLOW := \033[0;33m
CYAN   := \033[0;36m
RESET  := \033[0m

# ─── Main Commands ───────────────────────────────────────────────────────────

## Auto-detect host environment and write .env for docker compose
.env:
	@echo "# Auto-generated by Kronn — do not edit" > .env
	@uname_s=$$(uname -s 2>/dev/null); \
	if [ "$$uname_s" = "Darwin" ]; then \
		echo "KRONN_HOST_OS=macOS" >> .env; \
		if [ -d /opt/homebrew/bin ]; then \
			echo "KRONN_GLOBAL_BIN=/opt/homebrew/bin" >> .env; \
			echo "$(CYAN)  Detected macOS (Apple Silicon)$(RESET)"; \
		elif [ -d /usr/local/bin ]; then \
			echo "KRONN_GLOBAL_BIN=/usr/local/bin" >> .env; \
			echo "$(CYAN)  Detected macOS (Intel)$(RESET)"; \
		fi; \
	elif grep -qi "microsoft\|wsl" /proc/version 2>/dev/null; then \
		echo "KRONN_HOST_OS=WSL" >> .env; \
		echo "$(CYAN)  Detected WSL2$(RESET)"; \
	else \
		echo "KRONN_HOST_OS=Linux" >> .env; \
		echo "$(CYAN)  Detected Linux$(RESET)"; \
	fi
	@echo "KRONN_HOST_UID=$$(id -u)" >> .env
	@echo "KRONN_HOST_GID=$$(id -g)" >> .env
	@echo "UID=$$(id -u)" >> .env
	@echo "GID=$$(id -g)" >> .env
	@# Auto-detect repos dir = parent of Kronn install dir
	@repos_dir=$$(cd "$(CURDIR)/.." && pwd); \
	repos_rel=$${repos_dir#$$HOME/}; \
	echo "KRONN_REPOS_DIR=$$repos_dir" >> .env; \
	echo "KRONN_REPOS_REL=$$repos_rel" >> .env; \
	echo "$(CYAN)  Repos dir: $$repos_dir (rw mount)$(RESET)"
	@# Docker socket GID (for docker compose access from container)
	@if [ -S /var/run/docker.sock ]; then \
		docker_gid=$$(stat -c '%g' /var/run/docker.sock 2>/dev/null || echo ""); \
		if [ -n "$$docker_gid" ]; then \
			echo "KRONN_DOCKER_GID=$$docker_gid" >> .env; \
			echo "$(CYAN)  Docker socket GID: $$docker_gid$(RESET)"; \
		fi; \
	fi
	@# Auto-detect host system binary paths for terminal access
	@sysbin=""; \
	for dir in /usr/bin /usr/sbin /snap/bin; do \
		[ -d "$$dir" ] && sysbin="$${sysbin:+$$sysbin:}$$dir"; \
	done; \
	if [ -n "$$sysbin" ]; then \
		echo "KRONN_HOST_SYSBIN=$$sysbin" >> .env; \
		echo "$(CYAN)  Host system binaries: $$sysbin$(RESET)"; \
	fi
	@echo "# Add extra repo dirs (colon-separated) for rw access:" >> .env
	@echo "# KRONN_EXTRA_REPOS=$$HOME/Desktop/projects:$$HOME/Work" >> .env
	@# Ensure .claude.json exists as a file (Docker creates a directory if missing)
	@if [ ! -e "$$HOME/.claude.json" ]; then \
		echo '{}' > "$$HOME/.claude.json"; \
		echo "$(CYAN)  Created ~/.claude.json (empty file)$(RESET)"; \
	elif [ -d "$$HOME/.claude.json" ]; then \
		echo "$(YELLOW)  WARNING: ~/.claude.json is a directory — fixing$(RESET)"; \
		rmdir "$$HOME/.claude.json" 2>/dev/null && echo '{}' > "$$HOME/.claude.json" || \
		echo "$(RED)  ERROR: Cannot fix ~/.claude.json — remove it manually$(RESET)"; \
	fi

## Generate docker-compose.override.yml for extra repo dirs (KRONN_EXTRA_REPOS)
.PHONY: _gen-override
_gen-override:
	@extra_repos=$$(sed -n 's/^KRONN_EXTRA_REPOS=//p' .env | tail -n 1); \
	if [ -n "$$extra_repos" ]; then \
		echo "# Auto-generated — extra rw mounts from KRONN_EXTRA_REPOS" > docker-compose.override.yml; \
		echo "services:" >> docker-compose.override.yml; \
		echo "  backend:" >> docker-compose.override.yml; \
		echo "    volumes:" >> docker-compose.override.yml; \
		IFS=':'; for dir in $$extra_repos; do \
			rel=$${dir#$$HOME/}; \
			echo "      - $$dir:/host-home/$$rel:rw" >> docker-compose.override.yml; \
			echo "$(CYAN)  Extra rw mount: $$dir$(RESET)"; \
		done; \
	elif [ -f docker-compose.override.yml ]; then \
		rm -f docker-compose.override.yml; \
	fi

## Start everything (Docker, fast build — no LTO, ~4x faster than prod)
start: .env _gen-override
	@echo "$(GREEN)▸ Building $(APP_NAME) (fast profile)...$(RESET)"
	@CARGO_PROFILE=fast $(DOCKER_COMP) up -d --build
	@echo ""
	@echo "  $(CYAN)╭──╮$(RESET)"
	@echo "  $(CYAN)│$(GREEN)⚡$(CYAN)│$(RESET) $(GREEN)Kronn v0.1.0$(RESET)"
	@echo "  $(CYAN)╰──╯$(RESET) Services running."
	@echo ""
	@echo "       → $(GREEN)http://localhost:$(PORT)$(RESET)"
	@echo ""
	@echo "       $(CYAN)kronn stop$(RESET)     Stop"
	@echo "       $(CYAN)kronn logs$(RESET)     Logs"
	@echo "       $(CYAN)kronn restart$(RESET)  Restart"
	@echo ""

## Production build (Docker, release with LTO — slow but optimized binary)
start-prod: .env _gen-override
	@echo "$(GREEN)▸ Building $(APP_NAME) (production release)...$(RESET)"
	@$(DOCKER_COMP) up -d --build

## Stop all services
stop:
	@echo "$(YELLOW)▸ Stopping $(APP_NAME)...$(RESET)"
	@$(DOCKER_COMP) down
	@echo ""
	@echo "  $(CYAN)╭──╮$(RESET)"
	@echo "  $(CYAN)│$(RED)⚡$(CYAN)│$(RESET) $(RED)Kronn v0.1.0$(RESET)"
	@echo "  $(CYAN)╰──╯$(RESET) Services stopped."
	@echo ""

## Tail logs
logs:
	@$(DOCKER_COMP) logs -f

## Login to Kiro from the backend container (headless-safe OAuth device flow)
kiro-login: .env _gen-override
	@echo "$(CYAN)▸ Kiro login (device flow)...$(RESET)"
	@$(DOCKER_COMP) exec backend /bin/sh -lc 'set -e; PATH="$$HOME/.local/bin:$$PATH"; command -v kiro-cli >/dev/null 2>&1 || (command -v unzip >/dev/null 2>&1 || { echo "Missing unzip in backend image. Rebuild with make start."; exit 1; } ; echo "Installing kiro-cli in container..." ; curl -fsSL https://cli.kiro.dev/install | bash); kiro-cli login --use-device-flow'

## Clean everything
clean:
	@echo "$(YELLOW)▸ Cleaning up...$(RESET)"
	@$(DOCKER_COMP) down -v --remove-orphans
	@rm -rf backend/target frontend/node_modules frontend/dist
	@rm -f docker-compose.override.yml

## Production build (no Docker)
build:
	@echo "$(GREEN)▸ Building backend...$(RESET)"
	cd backend && cargo build --release
	@echo "$(GREEN)▸ Building frontend...$(RESET)"
	cd frontend && pnpm install && pnpm build
	@echo "$(GREEN)▸ Done. Binary at backend/target/release/$(APP_NAME)$(RESET)"

# ─── Development ─────────────────────────────────────────────────────────────

## Backend dev with hot reload
dev-backend:
	@echo "$(GREEN)▸ Starting backend (watch mode)...$(RESET)"
	cd backend && cargo watch -x run

## Frontend dev server
dev-frontend:
	@echo "$(GREEN)▸ Starting frontend dev server...$(RESET)"
	cd frontend && pnpm install && pnpm dev

## Run both in dev mode (requires tmux or two terminals)
dev:
	@echo "$(YELLOW)Run in two terminals:$(RESET)"
	@echo "  make dev-backend"
	@echo "  make dev-frontend"

# ─── Utilities ───────────────────────────────────────────────────────────────

## Check prerequisites
check:
	@echo "$(CYAN)Checking prerequisites...$(RESET)"
	@command -v docker >/dev/null 2>&1 && echo "  ✓ Docker" || echo "  ✗ Docker (required)"
	@command -v cargo  >/dev/null 2>&1 && echo "  ✓ Rust/Cargo" || echo "  ✗ Rust/Cargo (optional, for dev)"
	@command -v node   >/dev/null 2>&1 && echo "  ✓ Node.js" || echo "  ✗ Node.js (optional, for dev)"
	@command -v pnpm   >/dev/null 2>&1 && echo "  ✓ pnpm" || echo "  ✗ pnpm (optional, for dev)"

## Generate TypeScript types from Rust models
typegen:
	@echo "$(GREEN)▸ Generating TypeScript types...$(RESET)"
	cd backend && cargo test export_bindings -- --nocapture
	@echo "$(GREEN)▸ Types written to frontend/src/types/generated.ts$(RESET)"

## Run backend tests (skips ts-rs exports to avoid overwriting generated.ts)
test-backend:
	@echo "$(CYAN)▸ Running backend tests...$(RESET)"
	cd backend && cargo test --lib -- --skip export_bindings

## Run clippy lints in Docker (same toolchain as CI)
lint-backend:
	@echo "$(CYAN)▸ Running cargo clippy in Docker...$(RESET)"
	@docker build --target linter -f backend/Dockerfile backend/

## Run shell script tests (bats)
test-shell:
	@echo "$(CYAN)▸ Running shell tests...$(RESET)"
	@./tests/bats/run.sh

help:
	@echo ""
	@echo "$(CYAN)$(APP_NAME) — Enter the grid. Command your agents.$(RESET)"
	@echo ""
	@echo "$(GREEN)Usage:$(RESET)"
	@echo "  make start          Build & launch (Docker, fast — default)"
	@echo "  make start-prod     Build & launch (Docker, release + LTO)"
	@echo "  make stop           Stop services"
	@echo "  make logs           Tail logs"
	@echo "  make clean          Remove containers & data"
	@echo "  make build          Production build (native)"
	@echo "  make dev-backend    Rust hot reload"
	@echo "  make dev-frontend   Vite dev server"
	@echo "  make check          Verify prerequisites"
	@echo "  make kiro-login     Kiro OAuth login (device flow in container)"
	@echo "  make typegen        Sync Rust → TS types"
	@echo "  make test-shell     Run shell tests (bats)"
	@echo ""
