// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentProjectUsage = { project_id: string, project_name: string, tokens_used: bigint, message_count: number, };
