// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";

export type AgentDetection = { name: string, agent_type: AgentType, installed: boolean, enabled: boolean, path: string | null, version: string | null, latest_version: string | null, origin: string, install_command: string | null, host_managed: boolean, host_label: string | null, 
/**
 * Agent is runnable via npx/uvx fallback even when no local binary is found
 */
runtime_available: boolean, 
/**
 * `rtk` binary found on the host (PATH). Same value for every agent
 * detection in a given sweep, but kept per-agent so the frontend can
 * render the state inline without a separate endpoint.
 */
rtk_available: boolean, 
/**
 * The agent's own config file declares an RTK hook. Always `false` for
 * agents that have no shell-exec (API-only agents like Vibe) or no
 * hookable config (Ollama) — they're considered non-applicable.
 */
rtk_hook_configured: boolean, };
