// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConfig } from "./AgentConfig";
import type { ModelTiersConfig } from "./ModelTiersConfig";

export type AgentsConfig = { claude_code: AgentConfig, codex: AgentConfig, gemini_cli: AgentConfig, kiro: AgentConfig, vibe: AgentConfig, 
/**
 * Per-agent model tier overrides (Economy/Reasoning model names).
 */
model_tiers: ModelTiersConfig, };
