// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTier } from "./ModelTier";

export type AgentSettings = { 
/**
 * Explicit model override (expert mode). Takes priority over tier.
 */
model: string | null, 
/**
 * Abstract tier selection. Resolved to a concrete --model flag per agent.
 */
tier: ModelTier | null, reasoning_effort: string | null, max_tokens: bigint | null, };
