// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProjectUsage } from "./AgentProjectUsage";

export type AgentUsageSummary = { agent_type: string, total_tokens: bigint, message_count: number, by_project: Array<AgentProjectUsage>, };
