// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";

export type AgentDetection = { name: string, agent_type: AgentType, installed: boolean, enabled: boolean, path: string | null, version: string | null, latest_version: string | null, origin: string, install_command: string | null, host_managed: boolean, host_label: string | null, 
/**
 * Agent is runnable via npx/uvx fallback even when no local binary is found
 */
runtime_available: boolean, };
