// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileCategory } from "./ProfileCategory";

export type AgentProfile = { id: string, name: string, persona_name: string, role: string, avatar: string, color: string, category: ProfileCategory, persona_prompt: string, default_engine: string | null, is_builtin: boolean, 
/**
 * Estimated token cost when injected into an agent prompt (~4 chars = 1 token).
 */
token_estimate: number, };
