// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiConfigType } from "./AiConfigType";

export type AiConfigStatus = { detected: boolean, configs: Array<AiConfigType>, };
