// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuth2ExtraHeader } from "./OAuth2ExtraHeader";

export type ApiAuthKind = { "ApiKeyQuery": { param_name: string, env_key: string, } } | { "ApiKeyHeader": { header_name: string, env_key: string, } } | { "Bearer": { env_key: string, } } | { "Basic": { user_env: string, password_env: string, } } | { "BasicApiKey": { env_key: string, } } | { "OAuth2ClientCredentials": { token_url: string, client_id_env: string, client_secret_env: string, scope: string, extra_headers?: Array<OAuth2ExtraHeader>, } } | "None";
