// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-secret parameter the plugin instance needs (e.g. host, workspace id).
 * Stored in the same encrypted env blob as the API key, but the UI renders
 * these as plain inputs (no mask), and they're surfaced in the prompt
 * injection alongside the auth so the agent can build full URLs.
 */
export type ApiConfigKey = { env_key: string, label: string, placeholder: string, description: string, };
