// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiEndpoint = { path: string, 
/**
 * `"GET"`, `"POST"`, etc. Kept free-form to avoid constraining agents
 * that want to call a rare verb.
 */
method: string, description: string, };
