// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyDisplay } from "./ApiKeyDisplay";

export type ApiKeysResponse = { keys: Array<ApiKeyDisplay>, disabled_overrides: Array<string>, };
