// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKeyDisplay = { id: string, name: string, provider: string, masked_value: string, active: boolean, };
