// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { AgentsConfig } from "./AgentsConfig";
import type { ScanConfig } from "./ScanConfig";
import type { ServerConfig } from "./ServerConfig";
import type { TokensConfig } from "./TokensConfig";

export type AppConfig = { server: ServerConfig, tokens: TokensConfig, scan: ScanConfig, agents: AgentsConfig, language: string, disabled_agents: Array<AgentType>, };
