// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditKind =
    | "Full"
    | "Drift"
    | "Security"
    | "Docker"
    | "Performance"
    | "Accessibility"
    | "Rgaa"
    | "Database"
    | "ApiDesign"
    | "Custom";
