// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditFileInfo } from "./AuditFileInfo";
import type { AuditTodo } from "./AuditTodo";
import type { TechDebtItem } from "./TechDebtItem";

export type AuditInfo = { files: Array<AuditFileInfo>, todos: Array<AuditTodo>, tech_debt_items: Array<TechDebtItem>, };
