// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";

export type BootstrapProjectRequest = { name: string, description: string, agent: AgentType, mcp_config_ids: Array<string>, };
