// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanupOrphanEnvResponse = { configs_updated: number, total_keys_removed: number, };
