// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloneProjectResponse = { project_id: string, discussion_id: string | null, };
