// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillCategory } from "./SkillCategory";

export type CreateSkillRequest = { name: string, description: string, icon: string, category: SkillCategory, content: string, };
