// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMcpConfigRequest = { server_id: string, label: string, env: Record<string, string>, args_override: Array<string> | null, is_global: boolean, project_ids: Array<string>, };
