// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { ModelTier } from "./ModelTier";

export type CreateDiscussionRequest = { project_id: string | null, title: string, agent: AgentType, language: string, initial_prompt: string, skill_ids: Array<string>, profile_ids: Array<string>, directive_ids: Array<string>, workspace_mode: string | null, base_branch: string | null, 
/**
 * Model capability tier (economy / default / reasoning).
 */
tier: ModelTier, };
