// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAction } from "./WorkflowAction";
import type { WorkflowSafety } from "./WorkflowSafety";
import type { WorkflowStep } from "./WorkflowStep";
import type { WorkflowTrigger } from "./WorkflowTrigger";
import type { WorkspaceConfig } from "./WorkspaceConfig";

export type CreateWorkflowRequest = { name: string, project_id: string | null, trigger: WorkflowTrigger, steps: Array<WorkflowStep>, actions: Array<WorkflowAction>, safety: WorkflowSafety | null, workspace_config: WorkspaceConfig | null, concurrency_limit: number | null, };
