// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyUsage = { date: string, anthropic: bigint, openai: bigint, mistral: bigint, };
