// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProfile } from "./AgentProfile";
import type { Directive } from "./Directive";
import type { Discussion } from "./Discussion";
import type { McpConfig } from "./McpConfig";
import type { McpServer } from "./McpServer";
import type { Project } from "./Project";
import type { Skill } from "./Skill";
import type { Workflow } from "./Workflow";

export type DbExport = { version: number, exported_at: string, projects: Array<Project>, discussions: Array<Discussion>, workflows: Array<Workflow>, mcp_servers: Array<McpServer>, mcp_configs: Array<McpConfig>, custom_skills: Array<Skill>, custom_directives: Array<Directive>, custom_profiles: Array<AgentProfile>, };
