// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A detected network IP with its type.
 */
export type DetectedIp = { ip: string, 
/**
 * "tailscale", "vpn", or "lan"
 */
kind: string, label: string, };
