// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiConfigType } from "./AiConfigType";

export type DetectedRepo = { path: string, name: string, remote_url: string | null, branch: string, ai_configs: Array<AiConfigType>, has_project: boolean, hidden: boolean, };
