// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { MessageRole } from "./MessageRole";

export type DiscussionMessage = { id: string, role: MessageRole, content: string, agent_type: AgentType | null, timestamp: string, tokens_used: bigint, auth_mode: string | null, 
/**
 * Which model tier was used for this message (economy/default/reasoning).
 */
model_tier: string | null, 
/**
 * Author identity (for multi-user / display)
 */
author_pseudo: string | null, author_avatar_email: string | null, };
