// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { DiscussionMessage } from "./DiscussionMessage";
import type { ModelTier } from "./ModelTier";

export type Discussion = { id: string, project_id: string | null, title: string, agent: AgentType, language: string, participants: Array<AgentType>, messages: Array<DiscussionMessage>, message_count: number, skill_ids: Array<string>, profile_ids: Array<string>, directive_ids: Array<string>, archived: boolean, workspace_mode: string, workspace_path: string | null, worktree_branch: string | null, 
/**
 * Model capability tier for this discussion.
 */
tier: ModelTier, 
/**
 * Pin the first message (protocol prompt) — always include it in agent prompts, never summarize it.
 * Used for validation, bootstrap, and briefing discussions.
 */
pin_first_message: boolean, 
/**
 * Cached summary of older messages (eco-design: avoids re-sending full history).
 */
summary_cache: string | null, 
/**
 * Index of the last message included in summary_cache (0-based).
 */
summary_up_to_msg_idx: number | null, 
/**
 * Shared discussion UUID (None = local-only, Some = replicated with peers).
 */
shared_id: string | null, 
/**
 * Contact IDs this discussion is shared with.
 */
shared_with: Array<string>, created_at: string, updated_at: string, };
