// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteRepo } from "./RemoteRepo";
import type { RepoSource } from "./RepoSource";

export type DiscoverReposResponse = { repos: Array<RemoteRepo>, sources: Array<string>, available_sources: Array<RepoSource>, };
