// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoveredKey = { provider: string, source: string, suggested_name: string, already_exists: boolean, };
