// ╔═══════════════════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED by ts-rs — do not edit manually                        ║
// ║  Run `make typegen` to regenerate from Rust models                     ║
// ╚═══════════════════════════════════════════════════════════════════════════╝

// ─── Config ─────────────────────────────────────────────────────────────────

export interface AppConfig {
  server: ServerConfig;
  tokens: TokensConfig;
  scan: ScanConfig;
  agents: AgentsConfig;
  language: string;
}

export interface ServerConfig {
  host: string;
  port: number;
}

export interface TokensConfig {
  keys: ApiKey[];
  disabled_overrides: string[];
}

export interface ApiKey {
  id: string;
  name: string;
  provider: string;
  active: boolean;
}

export interface ApiKeyDisplay {
  id: string;
  name: string;
  provider: string;
  masked_value: string;
  active: boolean;
}

export interface SaveApiKeyRequest {
  id: string | null;
  name: string;
  provider: string;
  value: string;
}

export interface ApiKeysResponse {
  keys: ApiKeyDisplay[];
  disabled_overrides: string[];
}

export interface SaveTokensRequest {
  anthropic: string | null;
  openai: string | null;
}

export interface ScanConfig {
  paths: string[];
  ignore: string[];
  scan_depth: number;
}

export interface AgentsConfig {
  claude_code: AgentConfig;
  codex: AgentConfig;
  gemini_cli: AgentConfig;
  kiro: AgentConfig;
  vibe: AgentConfig;
}

export interface SetAgentAccessRequest {
  agent: AgentType;
  full_access: boolean;
}

export interface AgentConfig {
  path: string | null;
  installed: boolean;
  version: string | null;
  full_access: boolean;
}

// ─── Setup ──────────────────────────────────────────────────────────────────

export interface SetupStatus {
  is_first_run: boolean;
  current_step: SetupStep;
  agents_detected: AgentDetection[];
  scan_paths_set: boolean;
  repos_detected: DetectedRepo[];
  default_scan_path: string | null;
}

export type SetupStep = "Agents" | "ScanPaths" | "Detection" | "Complete";

export interface AgentDetection {
  name: string;
  agent_type: AgentType;
  installed: boolean;
  enabled: boolean;
  path: string | null;
  version: string | null;
  latest_version: string | null;
  origin: string;
  install_command: string | null;
  host_managed: boolean;
  host_label: string | null;
  /** Agent is runnable via npx/uvx fallback even when no local binary is found */
  runtime_available: boolean;
}

export type AgentType = "ClaudeCode" | "Codex" | "Vibe" | "GeminiCli" | "Kiro" | "Custom";

// ─── AI Audit ────────────────────────────────────────────────────────────────

export type AiAuditStatus = "NoTemplate" | "TemplateInstalled" | "Bootstrapped" | "Audited" | "Validated";

export interface LaunchAuditRequest {
  agent: AgentType;
}

export interface BootstrapProjectRequest {
  name: string;
  description: string;
  agent: AgentType;
  mcp_config_ids?: string[];
}

export interface BootstrapProjectResponse {
  project_id: string;
  discussion_id: string;
}

export interface CloneProjectRequest { url: string; name: string | null; agent: AgentType; }
export interface CloneProjectResponse { project_id: string; discussion_id: string | null; }

export interface RemoteRepo {
  name: string;
  full_name: string;
  clone_url: string;
  ssh_url: string;
  description: string | null;
  language: string | null;
  stargazers_count: number;
  updated_at: string;
  source: string;
  already_cloned: boolean;
}

export interface RepoSource {
  id: string;
  label: string;
  provider: string;
}

export interface DiscoverReposRequest {
  source_ids: string[];
}

export interface DiscoverReposResponse {
  repos: RemoteRepo[];
  sources: string[];
  available_sources: RepoSource[];
}

// ─── Projects ───────────────────────────────────────────────────────────────

export interface Project {
  id: string;
  name: string;
  path: string;
  repo_url: string | null;
  token_override: TokenOverride | null;
  ai_config: AiConfigStatus;
  audit_status: AiAuditStatus;
  ai_todo_count: number;
  default_skill_ids?: string[];
  created_at: string; // ISO 8601
  updated_at: string;
}

export interface TokenOverride {
  provider: string;
  token: string;
}

export interface AiConfigStatus {
  detected: boolean;
  configs: AiConfigType[];
}

export type AiConfigType = "ClaudeMd" | "ClauseDir" | "AiDir" | "CursorRules" | "ContinueDev" | "McpJson" | "Custom";

export interface DetectedRepo {
  path: string;
  name: string;
  remote_url: string | null;
  branch: string;
  ai_configs: AiConfigType[];
  has_project: boolean;
  hidden: boolean;
}

// ─── MCPs (new 3-tier model) ────────────────────────────────────────────────

export interface McpServer {
  id: string;
  name: string;
  description: string;
  transport: McpTransport;
  source: McpSource;
}

export type McpTransport =
  | { Stdio: { command: string; args: string[] } }
  | { Sse: { url: string } }
  | { Streamable: { url: string } };

export type McpSource = "Registry" | "Detected" | "Manual";

export interface McpConfig {
  id: string;
  server_id: string;
  label: string;
  env_keys: string[];
  env_encrypted: string;
  args_override: string[] | null;
  is_global: boolean;
  include_general: boolean;
  config_hash: string;
  project_ids: string[];
}

export interface McpConfigDisplay {
  id: string;
  server_id: string;
  server_name: string;
  label: string;
  env_keys: string[];
  env_masked: McpEnvEntry[];
  args_override: string[] | null;
  is_global: boolean;
  include_general: boolean;
  config_hash: string;
  project_ids: string[];
  project_names: string[];
}

export interface McpEnvEntry {
  key: string;
  masked_value: string;
}

export interface McpOverview {
  servers: McpServer[];
  configs: McpConfigDisplay[];
  customized_contexts: string[];
}

// Legacy types (kept for backward compatibility)
export interface McpDefinition {
  id: string;
  name: string;
  description: string;
  transport: McpTransport;
  env_keys: string[];
  tags: string[];
  token_url: string | null;
  token_help: string | null;
}

// ─── Workflows ─────────────────────────────────────────────────────────────

export interface Workflow {
  id: string;
  name: string;
  project_id: string | null;
  trigger: WorkflowTrigger;
  steps: WorkflowStep[];
  actions: WorkflowAction[];
  safety: WorkflowSafety;
  workspace_config: WorkspaceConfig | null;
  concurrency_limit: number | null;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

export type WorkflowTrigger =
  | { type: "Cron"; schedule: string }
  | { type: "Tracker"; source: TrackerSourceConfig; query: string; labels: string[]; interval: string }
  | { type: "Manual" };

export type TrackerSourceConfig =
  | { type: "GitHub"; owner: string; repo: string };

export interface WorkflowStep {
  name: string;
  agent: AgentType;
  prompt_template: string;
  mode: StepMode;
  mcp_config_ids?: string[];
  agent_settings?: AgentSettings | null;
  on_result?: StepConditionRule[];
  stall_timeout_secs?: number | null;
  retry?: RetryConfig | null;
  delay_after_secs?: number | null;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
}

export type StepMode =
  | { type: "Normal" };

export interface AgentSettings {
  model?: string | null;
  reasoning_effort?: string | null;
  max_tokens?: number | null;
}

export interface StepConditionRule {
  contains: string;
  action: ConditionAction;
}

export type ConditionAction =
  | { type: "Stop" }
  | { type: "Skip" }
  | { type: "Goto"; step_name: string };

export interface RetryConfig {
  max_retries: number;
  backoff: string;
}

export type WorkflowAction =
  | { type: "CreatePr"; title_template: string; body_template: string; branch_template: string }
  | { type: "CommentIssue"; body_template: string }
  | { type: "UpdateTrackerStatus"; status: string }
  | { type: "CreateIssue"; title_template: string; body_template: string };

export interface WorkflowSafety {
  sandbox: boolean;
  max_files?: number | null;
  max_lines?: number | null;
  require_approval: boolean;
}

export interface WorkspaceConfig {
  hooks: WorkspaceHooks;
}

export interface WorkspaceHooks {
  after_create?: string | null;
  before_run?: string | null;
  after_run?: string | null;
  before_remove?: string | null;
}

export interface WorkflowRun {
  id: string;
  workflow_id: string;
  status: RunStatus;
  trigger_context: WorkflowTrigger | null;
  step_results: StepResult[];
  tokens_used: number;
  workspace_path: string | null;
  started_at: string;
  finished_at: string | null;
}

export type RunStatus = "Pending" | "Running" | "Success" | "Failed" | "Cancelled" | "WaitingApproval";

export interface StepResult {
  step_name: string;
  status: RunStatus;
  output: string;
  tokens_used: number;
  duration_ms: number;
  condition_result?: string | null;
}

export interface WorkflowSummary {
  id: string;
  name: string;
  project_id: string | null;
  project_name: string | null;
  trigger_type: string;
  step_count: number;
  enabled: boolean;
  last_run: WorkflowRunSummary | null;
  created_at: string;
}

export interface WorkflowRunSummary {
  id: string;
  status: RunStatus;
  started_at: string;
  finished_at: string | null;
  tokens_used: number;
}

export interface CreateWorkflowRequest {
  name: string;
  project_id?: string | null;
  trigger: WorkflowTrigger;
  steps: WorkflowStep[];
  actions?: WorkflowAction[];
  safety?: WorkflowSafety | null;
  workspace_config?: WorkspaceConfig | null;
  concurrency_limit?: number | null;
}

export interface UpdateWorkflowRequest {
  name?: string;
  trigger?: WorkflowTrigger;
  steps?: WorkflowStep[];
  actions?: WorkflowAction[];
  safety?: WorkflowSafety;
  workspace_config?: WorkspaceConfig;
  concurrency_limit?: number | null;
  enabled?: boolean;
}

export interface ImportWorkflowRequest {
  content: string;
  project_id?: string | null;
}

// ─── AI Documentation Files ─────────────────────────────────────────────────

export interface AiFileNode {
  path: string;
  name: string;
  is_dir: boolean;
  children?: AiFileNode[];
}

export interface AiFileContent {
  path: string;
  content: string;
}

export interface AiSearchResult {
  path: string;
  match_count: number;
}

// ─── Stats ──────────────────────────────────────────────────────────────────

export interface TokenUsageSummary {
  total_tokens: number;
  by_provider: ProviderUsage[];
  by_project: ProjectUsage[];
  daily_history: DailyUsage[];
}

export interface ProviderUsage {
  provider: string;
  tokens_used: number;
  tokens_limit: number | null;
  cost_usd: number | null;
}

export interface ProjectUsage {
  project_id: string;
  project_name: string;
  tokens_used: number;
}

export interface DailyUsage {
  date: string;
  anthropic: number;
  openai: number;
  mistral: number;
}

export interface AgentUsageSummary {
  agent_type: string;
  total_tokens: number;
  message_count: number;
  by_project: AgentProjectUsage[];
}

export interface AgentProjectUsage {
  project_id: string;
  project_name: string;
  tokens_used: number;
  message_count: number;
}

// ─── Skills (WHAT — domain expertise, multi-select) ────────────────────────

export type SkillCategory = "Language" | "Domain" | "Business";

export interface Skill {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: SkillCategory;
  content: string;
  is_builtin: boolean;
}

export interface CreateSkillRequest {
  name: string;
  description: string;
  icon: string;
  category: SkillCategory;
  content: string;
}

// ─── Profiles (WHO — persona, multi-select) ────────────────────────────────

export type ProfileCategory = "Technical" | "Business" | "Meta";

export interface AgentProfile {
  id: string;
  name: string;
  persona_name: string;
  role: string;
  avatar: string;
  color: string;
  category: ProfileCategory;
  persona_prompt: string;
  default_engine?: string;
  is_builtin: boolean;
}

export interface CreateProfileRequest {
  name: string;
  persona_name: string;
  role: string;
  avatar: string;
  color: string;
  category: ProfileCategory;
  persona_prompt: string;
  default_engine?: string;
}

// ─── Directives (HOW — output behavior, multi-select) ──────────────────────

export type DirectiveCategory = "Output" | "Language";

export interface Directive {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: DirectiveCategory;
  content: string;
  is_builtin: boolean;
  conflicts?: string[];
}

export interface CreateDirectiveRequest {
  name: string;
  description: string;
  icon: string;
  category: DirectiveCategory;
  content: string;
  conflicts?: string[];
}

// ─── Discussions ────────────────────────────────────────────────────────────

export interface Discussion {
  id: string;
  project_id: string | null;
  title: string;
  agent: AgentType;
  language: string;
  participants: AgentType[];
  messages: DiscussionMessage[];
  message_count: number;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
  archived: boolean;
  created_at: string; // ISO 8601
  updated_at: string;
}

export interface DiscussionMessage {
  id: string;
  role: MessageRole;
  content: string;
  agent_type: AgentType | null;
  timestamp: string; // ISO 8601
  tokens_used: number;
  auth_mode: string | null;
}

export type MessageRole = "User" | "Agent" | "System";

// ─── MCP Context ───────────────────────────────────────────────────────────

export interface McpContextEntry {
  slug: string;
  label: string;
  content: string;
}

export interface UpdateMcpContextRequest {
  content: string;
}

// ─── API Requests ───────────────────────────────────────────────────────────

export interface SetScanPathsRequest {
  paths: string[];
}

export interface CreateMcpConfigRequest {
  server_id: string;
  label: string;
  env: Record<string, string>;
  args_override: string[] | null;
  is_global: boolean;
  project_ids: string[];
}

export interface UpdateMcpConfigRequest {
  label?: string;
  env?: Record<string, string>;
  args_override?: string[];
  is_global?: boolean;
  include_general?: boolean;
}

export interface LinkMcpConfigRequest {
  project_ids: string[];
}

export interface RevealSecretRequest {
  config_id: string;
}

export interface CreateDiscussionRequest {
  project_id: string | null;
  title: string;
  agent: AgentType;
  language?: string;
  initial_prompt: string;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
}

export interface SendMessageRequest {
  content: string;
  target_agent?: AgentType;
}

export interface OrchestrationRequest {
  agents: AgentType[];
  max_rounds?: number;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
}

export interface ServerConfigPublic {
  host: string;
  port: number;
  domain: string | null;
  max_concurrent_agents: number;
  auth_enabled: boolean;
}

export interface DbInfo {
  size_bytes: number;
  project_count: number;
  discussion_count: number;
  message_count: number;
  mcp_count: number;
  workflow_count: number;
  workflow_run_count: number;
  custom_skill_count: number;
  custom_profile_count: number;
  custom_directive_count: number;
}

export interface DbExport {
  version: number;
  exported_at: string;
  projects: Project[];
  discussions: Discussion[];
  workflows?: any[];
  mcp_servers?: any[];
  mcp_configs?: any[];
  custom_skills?: Skill[];
  custom_directives?: Directive[];
  custom_profiles?: AgentProfile[];
}
