// ╔═══════════════════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED by ts-rs — do not edit manually                        ║
// ║  Run `make typegen` to regenerate from Rust models                     ║
// ╚═══════════════════════════════════════════════════════════════════════════╝

// ─── Config ─────────────────────────────────────────────────────────────────

export interface AppConfig {
  server: ServerConfig;
  tokens: TokensConfig;
  scan: ScanConfig;
  agents: AgentsConfig;
  language: string;
}

export interface ServerConfig {
  host: string;
  port: number;
}

export interface TokensConfig {
  keys: ApiKey[];
  disabled_overrides: string[];
}

export interface ApiKey {
  id: string;
  name: string;
  provider: string;
  active: boolean;
}

export interface ApiKeyDisplay {
  id: string;
  name: string;
  provider: string;
  masked_value: string;
  active: boolean;
}

export interface SaveApiKeyRequest {
  id: string | null;
  name: string;
  provider: string;
  value: string;
}

export interface ApiKeysResponse {
  keys: ApiKeyDisplay[];
  disabled_overrides: string[];
}

export interface SaveTokensRequest {
  anthropic: string | null;
  openai: string | null;
}

export interface ScanConfig {
  paths: string[];
  ignore: string[];
  scan_depth: number;
}

export interface AgentsConfig {
  claude_code: AgentConfig;
  codex: AgentConfig;
  gemini_cli: AgentConfig;
  kiro: AgentConfig;
  vibe: AgentConfig;
  copilot_cli: AgentConfig;
  ollama: AgentConfig;
  model_tiers: ModelTiersConfig;
}

export type ModelTier = "economy" | "default" | "reasoning";

export interface ModelTierConfig {
  economy: string | null;
  reasoning: string | null;
}

export interface ModelTiersConfig {
  claude_code: ModelTierConfig;
  codex: ModelTierConfig;
  gemini_cli: ModelTierConfig;
  kiro: ModelTierConfig;
  vibe: ModelTierConfig;
  copilot_cli: ModelTierConfig;
  ollama: ModelTierConfig;
}

// ─── Ollama (0.4.0) ──────────────────────────────────────────────────

export interface OllamaModel {
  name: string;
  size: string;
  modified: string;
}

export interface OllamaHealthResponse {
  status: string;
  version: string | null;
  endpoint: string;
  models_count: number;
  hint: string | null;
}

export interface OllamaModelsResponse {
  models: OllamaModel[];
}

export interface SetAgentAccessRequest {
  agent: AgentType;
  full_access: boolean;
}

export interface AgentConfig {
  path: string | null;
  installed: boolean;
  version: string | null;
  full_access: boolean;
}

// ─── Setup ──────────────────────────────────────────────────────────────────

export interface SetupStatus {
  is_first_run: boolean;
  current_step: SetupStep;
  agents_detected: AgentDetection[];
  scan_paths_set: boolean;
  repos_detected: DetectedRepo[];
  default_scan_path: string | null;
}

export type SetupStep = "Agents" | "ScanPaths" | "Detection" | "Complete";

export interface AgentDetection {
  name: string;
  agent_type: AgentType;
  installed: boolean;
  enabled: boolean;
  path: string | null;
  version: string | null;
  latest_version: string | null;
  origin: string;
  install_command: string | null;
  host_managed: boolean;
  host_label: string | null;
  /** Agent is runnable via npx/uvx fallback even when no local binary is found */
  runtime_available: boolean;
  /** `rtk` binary found on the host (PATH). Same value for every agent detection in a given sweep. */
  rtk_available: boolean;
  /** Agent's config file declares an RTK hook. Always false for API-only (Vibe) or hookless (Ollama) agents. */
  rtk_hook_configured: boolean;
}

export type AgentType = "ClaudeCode" | "Codex" | "Vibe" | "GeminiCli" | "Kiro" | "CopilotCli" | "Ollama" | "Custom";

// ─── AI Audit ────────────────────────────────────────────────────────────────

export type AiAuditStatus = "NoTemplate" | "TemplateInstalled" | "Bootstrapped" | "Audited" | "Validated";

export interface LaunchAuditRequest {
  agent: AgentType;
}

/**
 * Live audit progress — snapshot of `AppState.audit_tracker.progress`.
 * Polled via `GET /api/projects/:id/audit-status` by ProjectCard to
 * resume the progress bar after tab/page navigation.
 * `phase` is one of "installing" | "auditing" | "validating" | "done".
 * `kind` is one of "full" | "partial" | "full_audit".
 */
export interface AuditProgress {
  project_id: string;
  phase: string;
  step_index: number;
  total_steps: number;
  current_file?: string | null;
  started_at: string;
  kind: string;
}

export interface BootstrapProjectRequest {
  name: string;
  description: string;
  agent: AgentType;
  mcp_config_ids?: string[];
  skill_ids?: string[];
}

export interface BootstrapProjectResponse {
  project_id: string;
  discussion_id: string;
}

export interface CloneProjectRequest { url: string; name: string | null; agent: AgentType; }
export interface CloneProjectResponse { project_id: string; discussion_id: string | null; }

export interface RemoteRepo {
  name: string;
  full_name: string;
  clone_url: string;
  ssh_url: string;
  description: string | null;
  language: string | null;
  stargazers_count: number;
  updated_at: string;
  source: string;
  already_cloned: boolean;
}

export interface RepoSource {
  id: string;
  label: string;
  provider: string;
}

export interface DiscoverReposRequest {
  source_ids: string[];
}

export interface DiscoverReposResponse {
  repos: RemoteRepo[];
  sources: string[];
  available_sources: RepoSource[];
}

// ─── Drift Detection ─────────────────────────────────────────────────────────

export interface DriftCheckResponse {
  audit_date: string | null;
  stale_sections: DriftSection[];
  fresh_sections: string[];
  total_sections: number;
}

export interface DriftSection {
  ai_file: string;
  audit_step: number;
  changed_sources: string[];
}

export interface PartialAuditRequest {
  agent: AgentType;
  steps: number[];
}

// ─── Projects ───────────────────────────────────────────────────────────────

export interface Project {
  id: string;
  name: string;
  path: string;
  repo_url: string | null;
  token_override: TokenOverride | null;
  ai_config: AiConfigStatus;
  audit_status: AiAuditStatus;
  ai_todo_count: number;
  default_skill_ids?: string[];
  briefing_notes?: string | null;
  created_at: string; // ISO 8601
  updated_at: string;
}

export interface TokenOverride {
  provider: string;
  token: string;
}

export interface AiConfigStatus {
  detected: boolean;
  configs: AiConfigType[];
}

export type AiConfigType = "ClaudeMd" | "ClauseDir" | "AiDir" | "CursorRules" | "ContinueDev" | "McpJson" | "Custom";

export interface DetectedRepo {
  path: string;
  name: string;
  remote_url: string | null;
  branch: string;
  ai_configs: AiConfigType[];
  has_project: boolean;
  hidden: boolean;
}

// ─── MCPs (new 3-tier model) ────────────────────────────────────────────────

export interface McpServer {
  id: string;
  name: string;
  description: string;
  transport: McpTransport;
  source: McpSource;
  /** REST API capability (present for API-only plugins like Chartbeat,
   *  or hybrid plugins that have both an MCP transport AND a REST API). */
  api_spec?: ApiSpec | null;
}

export type McpTransport =
  | { Stdio: { command: string; args: string[] } }
  | { Sse: { url: string } }
  | { Streamable: { url: string } }
  | "ApiOnly";

/** REST API capability for a plugin. */
export interface ApiSpec {
  base_url: string;
  auth: ApiAuthKind;
  endpoints: ApiEndpoint[];
  docs_url?: string | null;
  config_keys?: ApiConfigKey[];
}

export type ApiAuthKind =
  | { ApiKeyQuery: { param_name: string; env_key: string } }
  | { ApiKeyHeader: { header_name: string; env_key: string } }
  | { Bearer: { env_key: string } }
  | { OAuth2ClientCredentials: {
      token_url: string;
      client_id_env: string;
      client_secret_env: string;
      scope: string;
      extra_headers?: OAuth2ExtraHeader[];
    } }
  | "None";

export interface OAuth2ExtraHeader {
  name: string;
  value_template: string;
}

export interface ApiEndpoint {
  path: string;
  method: string;
  description: string;
}

export interface ApiConfigKey {
  env_key: string;
  label: string;
  placeholder: string;
  description: string;
}

export type McpSource = "Registry" | "Detected" | "Manual";

export interface McpConfig {
  id: string;
  server_id: string;
  label: string;
  env_keys: string[];
  env_encrypted: string;
  args_override: string[] | null;
  is_global: boolean;
  include_general: boolean;
  config_hash: string;
  project_ids: string[];
}

export interface McpConfigDisplay {
  id: string;
  server_id: string;
  server_name: string;
  label: string;
  env_keys: string[];
  env_masked: McpEnvEntry[];
  args_override: string[] | null;
  is_global: boolean;
  include_general: boolean;
  config_hash: string;
  project_ids: string[];
  project_names: string[];
  /** True when env_keys exist but decryption fails (secrets need re-entry). */
  secrets_broken: boolean;
}

export interface McpEnvEntry {
  key: string;
  masked_value: string;
}

export interface McpOverview {
  servers: McpServer[];
  configs: McpConfigDisplay[];
  customized_contexts: string[];
  incompatibilities: McpIncompatibility[];
}

export interface McpIncompatibility {
  server_id: string;
  agent: AgentType;
  reason: string;
}

// Legacy types (kept for backward compatibility)
export interface McpDefinition {
  id: string;
  name: string;
  description: string;
  transport: McpTransport;
  env_keys: string[];
  tags: string[];
  token_url: string | null;
  token_help: string | null;
  publisher: string;
  official: boolean;
  /** API capability (present for API-only plugins like Chartbeat, or
   *  hybrid plugins). Mirrored onto `McpServer.api_spec` at seed time. */
  api_spec?: ApiSpec | null;
}

// ─── Workflows ─────────────────────────────────────────────────────────────

export interface Workflow {
  id: string;
  name: string;
  project_id: string | null;
  trigger: WorkflowTrigger;
  steps: WorkflowStep[];
  actions: WorkflowAction[];
  safety: WorkflowSafety;
  workspace_config: WorkspaceConfig | null;
  concurrency_limit: number | null;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

export type WorkflowTrigger =
  | { type: "Cron"; schedule: string }
  | { type: "Tracker"; source: TrackerSourceConfig; query: string; labels: string[]; interval: string }
  | { type: "Manual" };

export type TrackerSourceConfig =
  | { type: "GitHub"; owner: string; repo: string };

export type StepOutputFormat =
  | { type: "FreeText" }
  | { type: "Structured" };

export interface WorkflowStep {
  name: string;
  step_type?: StepType;
  description?: string | null;
  agent: AgentType;
  prompt_template: string;
  mode: StepMode;
  output_format?: StepOutputFormat;
  mcp_config_ids?: string[];
  agent_settings?: AgentSettings | null;
  on_result?: StepConditionRule[];
  stall_timeout_secs?: number | null;
  retry?: RetryConfig | null;
  delay_after_secs?: number | null;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
  // ─── BatchQuickPrompt fields (Phase 2 batch workflows) ─────────────
  // Only meaningful when step_type.type === 'BatchQuickPrompt'.
  batch_quick_prompt_id?: string | null;
  batch_items_from?: string | null;
  batch_wait_for_completion?: boolean | null;
  batch_max_items?: number | null;
  /// "Direct" (default) or "Isolated" — per-child git worktree for parallel code writes.
  batch_workspace_mode?: string | null;
  /** Quick Prompt IDs to fire sequentially after the initial one inside each
   * child discussion. Progress only increments when the full chain finishes. */
  batch_chain_prompt_ids?: string[];
  // ─── Notify fields (0.3.5) ─────────────────────────────────────────
  // Only meaningful when step_type.type === 'Notify'.
  notify_config?: NotifyConfig | null;
}

/** Configuration for a Notify webhook step (zero agent tokens). */
export interface NotifyConfig {
  url: string;
  method: string;
  headers: Record<string, string>;
  body_template: string;
}

export type StepType =
  | { type: "Agent" }
  | { type: "ApiCall" }
  | { type: "BatchQuickPrompt" }
  | { type: "Notify" };

export type StepMode =
  | { type: "Normal" };

export interface AgentSettings {
  model?: string | null;
  tier?: ModelTier | null;
  reasoning_effort?: string | null;
  max_tokens?: number | null;
}

export interface StepConditionRule {
  contains: string;
  action: ConditionAction;
}

export type ConditionAction =
  | { type: "Stop" }
  | { type: "Skip" }
  | { type: "Goto"; step_name: string };

export interface RetryConfig {
  max_retries: number;
  backoff: string;
}

export type WorkflowAction =
  | { type: "CreatePr"; title_template: string; body_template: string; branch_template: string }
  | { type: "CommentIssue"; body_template: string }
  | { type: "UpdateTrackerStatus"; status: string }
  | { type: "CreateIssue"; title_template: string; body_template: string };

export interface WorkflowSafety {
  sandbox: boolean;
  max_files?: number | null;
  max_lines?: number | null;
  require_approval: boolean;
}

export interface WorkspaceConfig {
  hooks: WorkspaceHooks;
}

export interface WorkspaceHooks {
  after_create?: string | null;
  before_run?: string | null;
  after_run?: string | null;
  before_remove?: string | null;
}

export interface WorkflowRun {
  id: string;
  workflow_id: string;
  status: RunStatus;
  trigger_context: WorkflowTrigger | null;
  step_results: StepResult[];
  tokens_used: number;
  workspace_path: string | null;
  started_at: string;
  finished_at: string | null;
  /** "linear" (classic workflow runs) or "batch" (Phase 1b fan-out) */
  run_type?: string;
  /** Batch runs only: target number of child discussions */
  batch_total?: number;
  /** Batch runs only: number of child discussions that finished OK */
  batch_completed?: number;
  /** Batch runs only: number of child discussions that failed */
  batch_failed?: number;
  /** Batch runs only: display name in the sidebar group header */
  batch_name?: string | null;
}

export type RunStatus = "Pending" | "Running" | "Success" | "Failed" | "Cancelled" | "WaitingApproval";

export interface StepResult {
  step_name: string;
  status: RunStatus;
  output: string;
  tokens_used: number;
  duration_ms: number;
  condition_result?: string | null;
}

export interface WorkflowSummary {
  id: string;
  name: string;
  project_id: string | null;
  project_name: string | null;
  trigger_type: string;
  step_count: number;
  enabled: boolean;
  last_run: WorkflowRunSummary | null;
  created_at: string;
}

export interface WorkflowRunSummary {
  id: string;
  status: RunStatus;
  started_at: string;
  finished_at: string | null;
  tokens_used: number;
}

/** Compact summary of a batch workflow run, with its parent linear run
 *  resolved to (workflow name + run sequence). Feeds the sidebar pastille. */
export interface BatchRunSummary {
  run_id: string;
  batch_name: string | null;
  batch_total: number;
  status: RunStatus;
  /** Quick Prompt that this batch fans out — used as the sidebar folder label. */
  quick_prompt_id: string | null;
  quick_prompt_name: string | null;
  quick_prompt_icon: string | null;
  parent_run_id: string | null;
  parent_workflow_id: string | null;
  parent_workflow_name: string | null;
  parent_run_sequence: number | null;
}

export interface WorkflowSuggestion {
  id: string;
  title: string;
  description: string;
  reason: string;
  required_mcps: string[];
  audience: string;
  complexity: string;
  trigger: WorkflowTrigger;
  steps: WorkflowStep[];
}

export interface CreateWorkflowRequest {
  name: string;
  project_id?: string | null;
  trigger: WorkflowTrigger;
  steps: WorkflowStep[];
  actions?: WorkflowAction[];
  safety?: WorkflowSafety | null;
  workspace_config?: WorkspaceConfig | null;
  concurrency_limit?: number | null;
}

export interface UpdateWorkflowRequest {
  name?: string;
  project_id?: string | null;
  trigger?: WorkflowTrigger;
  steps?: WorkflowStep[];
  actions?: WorkflowAction[];
  safety?: WorkflowSafety;
  workspace_config?: WorkspaceConfig;
  concurrency_limit?: number | null;
  enabled?: boolean;
}

export interface ImportWorkflowRequest {
  content: string;
  project_id?: string | null;
}

// ─── AI Documentation Files ─────────────────────────────────────────────────

export interface AiFileNode {
  path: string;
  name: string;
  is_dir: boolean;
  children?: AiFileNode[];
}

export interface AiFileContent {
  path: string;
  content: string;
}

export interface AiSearchResult {
  path: string;
  match_count: number;
}

// ─── Stats ──────────────────────────────────────────────────────────────────

export interface TokenUsageSummary {
  total_tokens: number;
  total_cost_usd: number;
  discussion_tokens: number;
  workflow_tokens: number;
  by_provider: ProviderUsage[];
  by_project: ProjectUsage[];
  top_discussions: UsageEntry[];
  top_workflows: UsageEntry[];
  daily_history: DailyUsage[];
}

export interface UsageEntry {
  id: string;
  name: string;
  tokens_used: number;
  cost_usd: number;
}

export interface ProviderUsage {
  provider: string;
  tokens_used: number;
  tokens_limit: number | null;
  cost_usd: number | null;
}

export interface ProjectUsage {
  project_id: string;
  project_name: string;
  tokens_used: number;
  cost_usd: number;
}

export interface DailyUsage {
  date: string;
  tokens: number;
  cost_usd: number;
  anthropic: number;
  openai: number;
  google: number;
  mistral: number;
  amazon: number;
  github: number;
}

export interface AgentUsageSummary {
  agent_type: string;
  total_tokens: number;
  message_count: number;
  by_project: AgentProjectUsage[];
}

// ─── Context Files ──────────────────────────────────────────────────────────

export interface ContextFile {
  id: string;
  discussion_id: string;
  filename: string;
  mime_type: string;
  original_size: number;
  extracted_size: number;
  disk_path?: string | null;
  created_at: string;
}

export interface UploadContextFileResponse {
  file: ContextFile;
  suggested_skills: string[];
}

export interface AgentProjectUsage {
  project_id: string;
  project_name: string;
  tokens_used: number;
  message_count: number;
}

// ─── Skills (WHAT — domain expertise, multi-select) ────────────────────────

export type SkillCategory = "Language" | "Domain" | "Business";

export interface Skill {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: SkillCategory;
  content: string;
  is_builtin: boolean;
  token_estimate: number;
  /** agentskills.io: SPDX license identifier */
  license: string | null;
  /** agentskills.io: space-delimited list of pre-approved tools */
  allowed_tools: string | null;
  /** Auto-activation regexes by locale, declared in the skill's YAML
   *  frontmatter. When a message in the relevant locale matches any
   *  pattern, the frontend auto-adds this skill to the discussion. */
  auto_triggers?: AutoTriggers | null;
}

export interface AutoTriggers {
  /** Patterns that apply regardless of the discussion language.
   *  Usually language-independent tokens (format names, brand names). */
  common?: string[];
  /** Per-locale pattern buckets keyed by IETF language tag
   *  (`fr`, `en`, `es`, …). */
  locales?: Record<string, string[]>;
}

export interface CreateSkillRequest {
  name: string;
  description: string;
  icon: string;
  category: SkillCategory;
  content: string;
  license?: string | null;
  allowed_tools?: string | null;
}

// ─── Profiles (WHO — persona, multi-select) ────────────────────────────────

export type ProfileCategory = "Technical" | "Business" | "Meta";

export interface AgentProfile {
  id: string;
  name: string;
  persona_name: string;
  role: string;
  avatar: string;
  color: string;
  category: ProfileCategory;
  persona_prompt: string;
  default_engine?: string;
  is_builtin: boolean;
  token_estimate: number;
}

export interface CreateProfileRequest {
  name: string;
  persona_name: string;
  role: string;
  avatar: string;
  color: string;
  category: ProfileCategory;
  persona_prompt: string;
  default_engine?: string;
}

// ─── Directives (HOW — output behavior, multi-select) ──────────────────────

export type DirectiveCategory = "Output" | "Language";

export interface Directive {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: DirectiveCategory;
  content: string;
  is_builtin: boolean;
  conflicts?: string[];
  token_estimate: number;
  /** Optional URL to the upstream project for third-party adaptations (e.g. Caveman). */
  source_url?: string | null;
}

export interface CreateDirectiveRequest {
  name: string;
  description: string;
  icon: string;
  category: DirectiveCategory;
  content: string;
  conflicts?: string[];
}

// ─── Discussions ────────────────────────────────────────────────────────────

export interface Discussion {
  id: string;
  project_id: string | null;
  title: string;
  agent: AgentType;
  language: string;
  participants: AgentType[];
  messages: DiscussionMessage[];
  message_count: number;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
  tier?: ModelTier;
  archived: boolean;
  pinned: boolean;
  workspace_mode: string;
  workspace_path?: string | null;
  worktree_branch?: string | null;
  summary_cache?: string | null;
  summary_up_to_msg_idx?: number | null;
  shared_id?: string | null;
  shared_with?: string[];
  /** If set, this disc was spawned by a batch WorkflowRun — used for sidebar grouping */
  workflow_run_id?: string | null;
  /** Test mode — branch the main repo was on before the user entered test mode. */
  test_mode_restore_branch?: string | null;
  /** Test mode — auto-stash ref (kronn:auto-<disc_id>) pushed on enter, popped on exit. */
  test_mode_stash_ref?: string | null;
  created_at: string; // ISO 8601
  updated_at: string;
}

export interface DiscussionMessage {
  id: string;
  role: MessageRole;
  content: string;
  agent_type: AgentType | null;
  timestamp: string; // ISO 8601
  tokens_used: number;
  auth_mode: string | null;
  model_tier?: string | null;
  author_pseudo?: string | null;
  author_avatar_email?: string | null;
}

export type MessageRole = "User" | "Agent" | "System";

// ─── MCP Context ───────────────────────────────────────────────────────────

export interface McpContextEntry {
  slug: string;
  label: string;
  content: string;
}

export interface UpdateMcpContextRequest {
  content: string;
}

// ─── API Requests ───────────────────────────────────────────────────────────

export interface SetScanPathsRequest {
  paths: string[];
}

export interface CreateMcpConfigRequest {
  server_id: string;
  label: string;
  env: Record<string, string>;
  args_override: string[] | null;
  is_global: boolean;
  project_ids: string[];
}

export interface UpdateMcpConfigRequest {
  label?: string;
  env?: Record<string, string>;
  args_override?: string[];
  is_global?: boolean;
  include_general?: boolean;
}

export interface LinkMcpConfigRequest {
  project_ids: string[];
}

export interface RevealSecretRequest {
  config_id: string;
}

export interface CreateDiscussionRequest {
  project_id: string | null;
  title: string;
  agent: AgentType;
  language?: string;
  initial_prompt: string;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
  workspace_mode?: string;
  base_branch?: string;
  tier?: ModelTier;
}

export interface SendMessageRequest {
  content: string;
  target_agent?: AgentType;
}

export interface OrchestrationRequest {
  agents: AgentType[];
  max_rounds?: number;
  skill_ids?: string[];
  profile_ids?: string[];
  directive_ids?: string[];
}

export interface Contact {
  id: string;
  pseudo: string;
  avatar_email: string | null;
  kronn_url: string;
  invite_code: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface AddContactResult {
  contact: Contact;
  warning: string | null;
}

export type WsMessage =
  | { type: 'presence'; from_pseudo: string; from_invite_code: string; online: boolean }
  | { type: 'ping'; timestamp: number }
  | { type: 'pong'; timestamp: number }
  | { type: 'chat_message'; shared_discussion_id: string; message_id: string; from_pseudo: string; from_avatar_email: string | null; from_invite_code: string; content: string; timestamp: number }
  | { type: 'discussion_invite'; shared_discussion_id: string; title: string; from_pseudo: string; from_invite_code: string }
  | { type: 'batch_run_finished'; run_id: string; discussion_id: string; batch_name: string | null; batch_total: number; batch_completed: number; batch_failed: number }
  | { type: 'batch_run_progress'; run_id: string; discussion_id: string; batch_total: number; batch_completed: number; batch_failed: number }
  | { type: 'partial_response_recovered'; discussion_ids: string[] };

export interface DetectedIp {
  ip: string;
  kind: 'tailscale' | 'vpn' | 'lan';
  label: string;
}

export interface NetworkInfo {
  tailscale_ip: string | null;
  advertised_host: string;
  port: number;
  domain: string | null;
  detected_ips: DetectedIp[];
}

export interface ServerConfigPublic {
  host: string;
  port: number;
  domain: string | null;
  max_concurrent_agents: number;
  agent_stall_timeout_min: number;
  auth_enabled: boolean;
  pseudo: string | null;
  avatar_email: string | null;
  bio: string | null;
  debug_mode: boolean;
}

export interface DbInfo {
  size_bytes: number;
  project_count: number;
  discussion_count: number;
  message_count: number;
  mcp_count: number;
  workflow_count: number;
  workflow_run_count: number;
  custom_skill_count: number;
  custom_profile_count: number;
  custom_directive_count: number;
}

export interface DbExport {
  version: number;
  exported_at: string;
  projects: Project[];
  discussions: Discussion[];
  workflows?: any[];
  mcp_servers?: any[];
  mcp_configs?: any[];
  custom_skills?: Skill[];
  custom_directives?: Directive[];
  custom_profiles?: AgentProfile[];
  contacts?: Contact[];
}

export interface ImportResult {
  warnings: string[];
  invalid_paths: string[];
}

export interface TestStepRequest {
  step: WorkflowStep;
  project_id?: string | null;
  mock_previous_output?: string | null;
  mock_variables?: Record<string, string>;
  dry_run?: boolean;
}

export interface PromptVariable {
  name: string;
  label: string;
  placeholder: string;
  /** Human description of what this variable is for. Shown in batch UI. */
  description?: string | null;
  /** Must be filled before the prompt can run. Defaults to true. */
  required?: boolean;
}

export interface QuickPrompt {
  id: string;
  name: string;
  icon: string;
  prompt_template: string;
  variables: PromptVariable[];
  agent: AgentType;
  project_id?: string | null;
  skill_ids?: string[];
  tier?: ModelTier;
  /** Human description of what this Quick Prompt does. Shown in batch picker. */
  description?: string;
  created_at: string;
  updated_at: string;
}

export interface CreateQuickPromptRequest {
  name: string;
  icon?: string | null;
  prompt_template: string;
  variables?: PromptVariable[];
  agent?: AgentType | null;
  project_id?: string | null;
  skill_ids?: string[];
  tier?: ModelTier;
  description?: string;
}
