// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitCommitRequest = { files: Array<string>, message: string, amend: boolean, sign: boolean, };
