// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatus } from "./GitFileStatus";

export type GitStatusResponse = { branch: string, default_branch: string, is_default_branch: boolean, files: Array<GitFileStatus>, ahead: number, behind: number, has_upstream: boolean, provider: string, pr_url: string | null, };
