// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a config should be surfaced to the local CLIs (Claude Code, Gemini,
 * Codex, Copilot) when they run *outside* a Kronn-managed project.
 *
 * Separated from `is_global` (which is Kronn-internal: "applied across all
 * Kronn projects") because the two concepts answer different questions:
 * `is_global` decides Kronn project visibility; `host_sync` decides
 * whether Kronn writes the entry into `~/.claude.json` & friends.
 */
export type HostSyncMode = "None" | "GlobalOnly" | "MirrorAll";
