// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { AuditKind } from "./AuditKind";
import type { ModelTier } from "./ModelTier";

export type LaunchAuditRequest = {
    agent: AgentType,
    tier?: ModelTier | null,
    kind?: AuditKind | null,
    custom_prompt?: string | null,
    resume_run_id?: string | null,
};
