// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSyncMode } from "./HostSyncMode";
import type { McpEnvEntry } from "./McpEnvEntry";

/**
 * Display-safe version of McpConfig (secrets masked)
 */
export type McpConfigDisplay = { id: string, server_id: string, server_name: string, label: string, env_keys: Array<string>, env_masked: Array<McpEnvEntry>, args_override: Array<string> | null, is_global: boolean, include_general: boolean, config_hash: string, project_ids: Array<string>, project_names: Array<string>, 
/**
 * True when env_keys exist but decryption fails (secrets need re-entry).
 */
secrets_broken: boolean, 
/**
 * See `McpConfig::host_sync`.
 */
host_sync: HostSyncMode, };
