// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured instance of an MCP server — with label, env secrets, etc.
 * Multiple projects can share the same config (deduplication by config_hash).
 */
export type McpConfig = { id: string, server_id: string, label: string, env_keys: Array<string>, env_encrypted: string, args_override: Array<string> | null, is_global: boolean, include_general: boolean, config_hash: string, project_ids: Array<string>, };
