// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpEnvEntry } from "./McpEnvEntry";

/**
 * Display-safe version of McpConfig (secrets masked)
 */
export type McpConfigDisplay = { id: string, server_id: string, server_name: string, label: string, env_keys: Array<string>, env_masked: Array<McpEnvEntry>, args_override: Array<string> | null, is_global: boolean, include_general: boolean, config_hash: string, project_ids: Array<string>, project_names: Array<string>, };
