// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpTransport } from "./McpTransport";

/**
 * Registry entry — an MCP available for installation
 */
export type McpDefinition = { id: string, name: string, description: string, transport: McpTransport, env_keys: Array<string>, tags: Array<string>, token_url: string | null, token_help: string | null, };
