// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";

/**
 * A known incompatibility between an MCP server and a specific agent.
 */
export type McpIncompatibility = { 
/**
 * The MCP server ID (e.g. "mcp-gitlab", "detected:data-gouv-fr")
 */
server_id: string, 
/**
 * The agent that is incompatible
 */
agent: AgentType, 
/**
 * Human-readable explanation
 */
reason: string, };
