// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An MCP config whose declared env keys aren't all populated. The
 * scanner skips writing this entry into project-level config files
 * (`.mcp.json`, `.kiro/settings/mcp.json`, `.gemini/settings.json`,
 * `~/.codex/config.toml`) so the agent doesn't choke on a broken
 * MCP at startup. The UI surfaces this so the operator knows which
 * plugin to fix.
 */
export type McpIncompleteConfig = { 
/**
 * MCP config DB id.
 */
config_id: string, 
/**
 * User-facing label of the config (e.g. "Adobe Analytics", "GitLab Euronews").
 */
label: string, 
/**
 * Server name behind this config (helps the user remember which plugin).
 */
server_name: string, 
/**
 * The declared env_keys whose decrypted value is missing or empty.
 * Empty when the issue is decryption failure (the cipher itself is
 * gone, e.g. after a key rotation) — the UI shows a generic
 * "secrets unreadable" hint in that case.
 */
missing_keys: Array<string>, 
/**
 * Free-form reason — `missing_keys` for a key-by-key gap, or a
 * short error message for decryption failures.
 */
reason: string, };
