// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpConfigDisplay } from "./McpConfigDisplay";
import type { McpIncompatibility } from "./McpIncompatibility";
import type { McpIncompleteConfig } from "./McpIncompleteConfig";
import type { McpServer } from "./McpServer";

export type McpOverview = { servers: Array<McpServer>, configs: Array<McpConfigDisplay>, 
/**
 * Set of "slug:projectId" pairs where the context file has been customized (not default template).
 */
customized_contexts: Array<string>, 
/**
 * Known incompatibilities between MCP servers and agents.
 */
incompatibilities: Array<McpIncompatibility>, 
/**
 * Configs that declare `env_keys` but have empty/missing values for
 * at least one of them — those would fail handshake at agent boot
 * (Connection closed, OAuth invalid_client, etc.) AND poison the
 * per-agent startup latency. Kronn skips them at sync time and the
 * UI surfaces them as warnings so the operator can complete the
 * config or remove the entry.
 */
incomplete_configs: Array<McpIncompleteConfig>, };
