// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpConfigDisplay } from "./McpConfigDisplay";
import type { McpIncompatibility } from "./McpIncompatibility";
import type { McpServer } from "./McpServer";

export type McpOverview = { servers: Array<McpServer>, configs: Array<McpConfigDisplay>, 
/**
 * Set of "slug:projectId" pairs where the context file has been customized (not default template).
 */
customized_contexts: Array<string>, 
/**
 * Known incompatibilities between MCP servers and agents.
 */
incompatibilities: Array<McpIncompatibility>, };
