// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiSpec } from "./ApiSpec";
import type { McpSource } from "./McpSource";
import type { McpTransport } from "./McpTransport";

/**
 * An MCP server type (e.g. "GitHub", "Atlassian", "Context7").
 *
 * A plugin can have MCP capability (via `transport`), API capability (via
 * `api_spec`), or BOTH — e.g. Jira exposes both a `@modelcontextprotocol`
 * server and a REST API, and a hybrid plugin lets the agent pick the
 * right tool. API-only plugins use `McpTransport::ApiOnly` as a sentinel.
 */
export type McpServer = { id: string, name: string, description: string, transport: McpTransport, source: McpSource, 
/**
 * When present, the plugin exposes a REST API. Emitted into the agent's
 * `--append-system-prompt` as a `=== AVAILABLE APIs ===` block so the
 * agent can call it via curl (vs. MCP-style tools). NULL = MCP only.
 */
api_spec?: ApiSpec | null, };
