// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpSource } from "./McpSource";
import type { McpTransport } from "./McpTransport";

/**
 * An MCP server type (e.g. "GitHub", "Atlassian", "Context7")
 * Represents the abstract definition — command + args template.
 */
export type McpServer = { id: string, name: string, description: string, transport: McpTransport, source: McpSource, };
