// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Abstract model capability tier. Kronn maps each tier to a concrete --model flag per agent.
 * Priority: AgentSettings.model (explicit) > ModelTier > Default (no flag).
 */
export type ModelTier = "economy" | "default" | "reasoning";
