// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-agent model tier configuration. Maps Economy/Reasoning to concrete model names.
 * Stored in config.toml under [agents.model_tiers].
 */
export type ModelTierConfig = { economy: string | null, reasoning: string | null, };
