// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedIp } from "./DetectedIp";

/**
 * Network info for multi-user connectivity.
 */
export type NetworkInfo = { 
/**
 * Detected Tailscale IPv4 address (100.x.x.x), if available.
 */
tailscale_ip: string | null, 
/**
 * The host used in invite codes (domain > tailscale > host).
 */
advertised_host: string, 
/**
 * Backend port.
 */
port: number, 
/**
 * Configured domain, if any.
 */
domain: string | null, 
/**
 * All detected network IPs (tailscale, vpn, lan).
 */
detected_ips: Array<DetectedIp>, };
