// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Static header rendered alongside the `Authorization: Bearer` from an
 * OAuth2 exchange. Used for providers (Adobe Analytics, some Salesforce
 * endpoints) that require extra identification headers beyond the
 * bearer token. `value_template` supports `{ENV_KEY}` substitution from
 * the config's env map.
 */
export type OAuth2ExtraHeader = { name: string, value_template: string, };
