// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";

export type OrchestrationRequest = { agents: Array<AgentType>, max_rounds: number | null, skill_ids: Array<string>, profile_ids: Array<string>, directive_ids: Array<string>, };
