// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { ModelTier } from "./ModelTier";

export type PartialAuditRequest = { agent: AgentType, tier?: ModelTier | null, steps: Array<number>, };
