// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiAuditStatus } from "./AiAuditStatus";
import type { AiConfigStatus } from "./AiConfigStatus";
import type { TokenOverride } from "./TokenOverride";

export type Project = { id: string, name: string, path: string, repo_url: string | null, token_override: TokenOverride | null, ai_config: AiConfigStatus, audit_status: AiAuditStatus, ai_todo_count: number, default_skill_ids: Array<string>, default_profile_id: string | null, briefing_notes: string | null, created_at: string, updated_at: string, };
