// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveApiKeyRequest = { id: string | null, name: string, provider: string, value: string, };
