// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanConfig = { paths: Array<string>, ignore: Array<string>, 
/**
 * Max depth when scanning for git repos (2–10, default 4)
 */
scan_depth: number, };
