// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerConfig = { host: string, port: number, 
/**
 * Custom domain for CORS and TLS (e.g. "kronn.local")
 */
domain: string | null, 
/**
 * Maximum concurrent agent processes (default: 5)
 */
max_concurrent_agents: number, 
/**
 * Agent stall timeout in minutes — abort if no output for this long (default: 5)
 */
agent_stall_timeout_min: number, 
/**
 * User identity — displayed in messages and used for future multi-user
 */
pseudo: string | null, 
/**
 * Email for Gravatar avatar (optional, decoupled from git)
 */
avatar_email: string | null, };
