// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillCategory } from "./SkillCategory";

export type Skill = { id: string, name: string, description: string, icon: string, category: SkillCategory, content: string, is_builtin: boolean, 
/**
 * Estimated token cost when injected into an agent prompt (~4 chars = 1 token).
 */
token_estimate: number, };
