// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";

export type StepResult = { step_name: string, status: RunStatus, output: string, tokens_used: bigint, duration_ms: bigint, 
/**
 * What happened after this step: null = continued normally, or the condition action triggered.
 */
condition_result: string | null, };
