// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionAction } from "./ConditionAction";

export type StepConditionRule = { contains: string, action: ConditionAction, };
