// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyUsage } from "./DailyUsage";
import type { ProjectUsage } from "./ProjectUsage";
import type { ProviderUsage } from "./ProviderUsage";

export type TokenUsageSummary = { total_tokens: bigint, by_provider: Array<ProviderUsage>, by_project: Array<ProjectUsage>, daily_history: Array<DailyUsage>, };
