// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKey } from "./ApiKey";

export type TokensConfig = { 
/**
 * Legacy fields — kept for backward compat when reading old config.toml
 */
anthropic: string | null, openai: string | null, google: string | null, 
/**
 * All API keys (new multi-key system)
 */
keys: Array<ApiKey>, disabled_overrides: Array<string>, };
