// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServer } from "./McpServer";

/**
 * 0.8.6 (#60) — response wrapper for PUT /api/mcps/custom/:server_id.
 * Surfaces orphan env keys (slugs that vanished from
 * `api_spec.config_keys` but still exist in at least one linked
 * config's encrypted env). The frontend reads this and offers a
 * one-click cleanup so the user doesn't ship orphan secrets to disk
 * via the next host_sync pass.
 */
export type UpdateCustomSpecResponse = {
  server: McpServer,
  /**
   * Keys that were removed from the spec (or renamed) but still
   * exist in at least one linked config's stored env. Sorted alpha
   * for deterministic UI rendering. Empty when no rename / removal
   * happened (most common case).
   */
  orphan_env_keys: Array<string>,
};
