// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { ModelTier } from "./ModelTier";

export type UpdateDiscussionRequest = { title: string | null, archived: boolean | null, skill_ids: Array<string> | null, profile_ids: Array<string> | null, directive_ids: Array<string> | null, 
/**
 * Change project: Some(Some("id")) = set, Some(None) = unset, absent = no change
 */
project_id: string | null | null, 
/**
 * Change model tier for this discussion.
 */
tier: ModelTier | null, 
/**
 * Switch the primary agent for this discussion.
 */
agent: AgentType | null, };
