// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateMcpConfigRequest = { label: string | null, env: Record<string, string> | null, args_override: Array<string> | null, is_global: boolean | null, include_general: boolean | null, };
