// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceHooks = { after_create: string | null, before_run: string | null, after_run: string | null, before_remove: string | null, };
