// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceHooks } from "./WorkspaceHooks";

export type WorkspaceConfig = { hooks: WorkspaceHooks, };
