// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunSummary } from "./WorkflowRunSummary";

export type WorkflowSummary = { id: string, name: string, project_id: string | null, project_name: string | null, trigger_type: string, step_count: number, enabled: boolean, last_run: WorkflowRunSummary | null, created_at: string, };
