// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettings } from "./AgentSettings";
import type { AgentType } from "./AgentType";
import type { RetryConfig } from "./RetryConfig";
import type { StepConditionRule } from "./StepConditionRule";
import type { StepMode } from "./StepMode";
import type { StepType } from "./StepType";

export type WorkflowStep = { name: string, step_type: StepType, description: string | null, agent: AgentType, prompt_template: string, mode: StepMode, mcp_config_ids: Array<string>, agent_settings: AgentSettings | null, on_result: Array<StepConditionRule>, stall_timeout_secs: bigint | null, retry: RetryConfig | null, delay_after_secs: bigint | null, skill_ids: Array<string>, profile_ids: Array<string>, directive_ids: Array<string>, };
