// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowSafety = { sandbox: boolean, max_files: number | null, max_lines: number | null, require_approval: boolean, };
