#!/usr/bin/env bash
#
# Start a Kronn backend that cannot reach the instance you are working in.
#
# E2E specs that enrol credentials, rotate the publication bootstrap or seed
# hundreds of rows need a backend of their own. Pointing one at the developer's
# data directory is not a test — it is damage, and the damage is quiet.
#
# Two traps this script exists to close, both met for real on 2026-09-12:
#
#   1. `KRONN_DATA_DIR=<tmp> kronn` does NOT give you a sandbox port. With no
#      config.toml the backend writes one using the DEFAULT port — 3140, the
#      port the developer's own backend is on. So the config is generated by a
#      first pass bound to an address that cannot be assigned, which writes the
#      file and cannot serve anything.
#
#   2. A health check is not proof that YOUR process answered it. A previous
#      sandbox still holding the port replies 200 to everything, including
#      after its data directory has been deleted from underneath it — and the
#      run that follows reads a secret file that belongs to a database nobody
#      is serving. So the listener's pid is compared with the pid we started.
#
# Usage:  scripts/e2e-sandbox-backend.sh <data-dir> <port>
# Prints: the pid on stdout. Kill it with that pid, not with a pattern — the
#         process shows up as `./target/debug/kronn`, so a `pkill -f` on the
#         worktree path matches nothing.

set -euo pipefail

DATA_DIR="${1:?usage: e2e-sandbox-backend.sh <data-dir> <port>}"
PORT="${2:?usage: e2e-sandbox-backend.sh <data-dir> <port>}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BINARY="${KRONN_E2E_BINARY:-$ROOT/target/debug/kronn}"

if [[ "$PORT" == "3140" || "$PORT" == "5173" ]]; then
    echo "refusing port $PORT: that is the developer instance" >&2
    exit 1
fi
if lsof -nP -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "port $PORT is already served — stop that process first, by pid" >&2
    exit 1
fi
if [[ ! -x "$BINARY" ]]; then
    echo "no backend binary at $BINARY (cargo build --bin kronn)" >&2
    exit 1
fi

mkdir -p "$DATA_DIR"

if [[ ! -f "$DATA_DIR/config.toml" ]]; then
    # 127.0.0.2 is routed to the loopback on macOS but not assigned, so this
    # pass writes config.toml and can bind nothing at all — least of all 3140.
    KRONN_DATA_DIR="$DATA_DIR" KRONN_HOST=127.0.0.2 "$BINARY" \
        >"$DATA_DIR/bootstrap.log" 2>&1 &
    seeder=$!
    for _ in $(seq 1 60); do
        [[ -f "$DATA_DIR/config.toml" ]] && break
        sleep 0.5
    done
    kill "$seeder" 2>/dev/null || true
    wait "$seeder" 2>/dev/null || true
    [[ -f "$DATA_DIR/config.toml" ]] || { echo "config.toml was never written" >&2; exit 1; }
fi

# `sed -i ''` is the BSD form; GNU sed takes `-i` alone.
if sed --version >/dev/null 2>&1; then
    sed -i -E "s/^port = [0-9]+$/port = $PORT/" "$DATA_DIR/config.toml"
else
    sed -i '' -E "s/^port = [0-9]+$/port = $PORT/" "$DATA_DIR/config.toml"
fi
grep -q "^port = $PORT$" "$DATA_DIR/config.toml" || { echo "port not set" >&2; exit 1; }

KRONN_DATA_DIR="$DATA_DIR" KRONN_HOST=127.0.0.1 "$BINARY" >"$DATA_DIR/backend.log" 2>&1 &
backend=$!

for _ in $(seq 1 90); do
    kill -0 "$backend" 2>/dev/null || { echo "backend exited: $(tail -1 "$DATA_DIR/backend.log")" >&2; exit 1; }
    if curl -fsS -o /dev/null "http://127.0.0.1:$PORT/api/health" 2>/dev/null; then
        break
    fi
    sleep 1
done

listener="$(lsof -nP -iTCP:"$PORT" -sTCP:LISTEN -t 2>/dev/null | head -1)"
if [[ "$listener" != "$backend" ]]; then
    kill "$backend" 2>/dev/null || true
    echo "port $PORT is served by pid ${listener:-nobody}, not by the backend just started ($backend)" >&2
    exit 1
fi

echo "$backend"
